version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=iread
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234

  redis:
    image: redis:5.0.3-alpine
    ports:
      - "6379:6379"

volumes:
  mysql-data:
